version: '3.4'
services:
  db:
    image: postgres:10-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=bullet
      - POSTGRES_PASSWORD=bullet
      - POSTGRES_DB=bullet
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  web:
    build:
      context: .
      target: basebuild
    image: bullet
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=bullet.settings.development
      - PARENT_HOST=localhost:8000
    ports:
      - "8000:8000"
    volumes:
      - ./bullet/:/app/
    depends_on:
      - db
    command: ./entrypoint.sh

  tailwind:
    build:
      context: .
      target: cssbuild
    volumes:
      - ./bullet/:/app/bullet/
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./package.json:/app/package.json
    tty: true

volumes:
  postgres_data:
