version: '3.4'
services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=bullet
      - POSTGRES_PASSWORD=bullet
      - POSTGRES_DB=bullet
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  web:
    build:
      context: .
    image: bullet
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=bullet.settings.development
      - PARENT_HOST=localhost:8000
    ports:
      - "8000:8000"
    volumes:
      - ./bullet/:/app/
      - geiop_data:/geoip/
    depends_on:
      - db
      - geoip
      - meilisearch
    command: ./entrypoint.sh

  tailwind:
    build:
      context: .
      target: cssbuild
    volumes:
      - ./bullet/:/app/bullet/
      - ./css:/app/css/
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./package.json:/app/package.json
    tty: true

  geoip:
    image: maxmindinc/geoipupdate
    env_file:
      - .env
    volumes:
      -  geiop_data:/usr/share/GeoIP

  meilisearch:
    image: getmeili/meilisearch:v0.28
    volumes:
      - search_data:/meili_data

volumes:
  postgres_data:
  geiop_data:
  search_data:
